// Parts are generated by build_runner. Run `dart run build_runner build` first.
import 'dart:convert';

import 'package:chiffondb/chiffondb.dart';

part 'social_graph.g.dart';
part 'social_graph.chiffondb_store.dart';

// ---- Schema definitions ----

@NodeType()
class Person {
  @Id()
  RecordId? id;
  String name = '';
  int age = 0;
}

@NodeType()
class Company {
  @Id()
  RecordId? id;
  String name = '';
  String industry = '';
}

@EdgeType<Person, Person>()
class Follows {
  @Id()
  RecordId? id;
  DateTime since = DateTime.now();
}

@EdgeType<Person, Company>()
class WorksAt {
  @Id()
  RecordId? id;
  String role = '';
}

// ---- Usage example ----

Future<void> main() async {
  await ChiffonDb.init();
  final conn = await Connection.open(path: 'social.db');
  final store = ChiffonStore(conn);

  // Apply all schemas (idempotent).
  await store.applyAllSchemas();

  // Insert nodes.
  final aliceId = await store.insertPerson(
    Person()
      ..name = 'Alice'
      ..age = 30,
  );

  final bobId = await store.insertPerson(
    Person()
      ..name = 'Bob'
      ..age = 25,
  );

  final acmeId = await store.insertCompany(
    Company()
      ..name = 'ACME Corp'
      ..industry = 'Technology',
  );

  // Insert edges.
  await store.insertFollows(aliceId, bobId, Follows()..since = DateTime.now());
  await store.insertWorksAt(aliceId, acmeId, WorksAt()..role = 'Engineer');

  // Fetch by id.
  final alice = await store.getPerson(aliceId);
  print('name: ${alice?.name}, age: ${alice?.age}');

  // Fetch all.
  final persons = await store.listPersons();
  for (final p in persons) {
    print('  - ${p.name}');
  }

  await conn.close();
}
